-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 15:56:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DER_blog_pessoal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DER_blog_pessoal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DER_blog_pessoal` DEFAULT CHARACTER SET utf8 ;
USE `DER_blog_pessoal` ;

-- -----------------------------------------------------
-- Table `DER_blog_pessoal`.`db_pizzaria_legal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_blog_pessoal`.`db_pizzaria_legal` (
  `id` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER_blog_pessoal`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_blog_pessoal`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER_blog_pessoal`.`tb_Temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_blog_pessoal`.`tb_Temas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER_blog_pessoal`.`tb_Postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_blog_pessoal`.`tb_Postagens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `data` DATE NULL,
  `tb_usuario_id` BIGINT NOT NULL,
  `tb_Temas_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_Postagens_tb_usuario_idx` (`tb_usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_Postagens_tb_Temas1_idx` (`tb_Temas_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_Postagens_tb_usuario`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `DER_blog_pessoal`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Postagens_tb_Temas1`
    FOREIGN KEY (`tb_Temas_id`)
    REFERENCES `DER_blog_pessoal`.`tb_Temas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
